# Generated by Django 6.0.3 on 2026-05-12 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogs',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=36, null=True)),
                ('action', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('table_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, null=True)),
                ('record_id', models.CharField(blank=True, max_length=36, null=True)),
                ('old_data', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('new_data', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('ip_address', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=45, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'audit_logs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_type', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', default='pending', max_length=20)),
                ('confirmation_code', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, unique=True)),
                ('notes', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bookings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Governorates',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name_ar', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('name_en', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'governorates',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HotelRooms',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('room_type', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.SmallIntegerField()),
                ('available_count', models.SmallIntegerField()),
                ('description_ar', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500, null=True)),
                ('description_en', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hotel_rooms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('description_ar', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('description_en', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('stars', models.SmallIntegerField()),
                ('contact_phone', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('address', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('cover_image', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500, null=True)),
                ('is_active', models.BooleanField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'hotels',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('title_ar', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('title_en', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('content_ar', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
                ('content_en', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
                ('category', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, null=True)),
                ('display_order', models.SmallIntegerField()),
                ('is_active', models.BooleanField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'instructions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, unique=True)),
                ('description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'permissions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('phone_encrypted', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('failed_logins', models.SmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BookingGuests',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('national_id_encrypted', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500, null=True)),
                ('nationality', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, null=True)),
                ('person_type', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10)),
                ('phone_encrypted', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.bookings')),
            ],
            options={
                'db_table': 'booking_guests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HotelBookings',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.bookings')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.hotelrooms')),
            ],
            options={
                'db_table': 'hotel_bookings',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='hotelrooms',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.hotels'),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('method', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EGP', max_length=10)),
                ('status', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('gateway_response', models.TextField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.bookings')),
            ],
            options={
                'db_table': 'payments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CardPayments',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('card_holder', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150)),
                ('last4', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=4)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.payments')),
            ],
            options={
                'db_table': 'card_payments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BankTransfers',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('account_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150)),
                ('reference', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.payments')),
            ],
            options={
                'db_table': 'bank_transfers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name_ar', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('name_en', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('category', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=30)),
                ('description_ar', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('description_en', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('cover_image', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500, null=True)),
                ('is_active', models.BooleanField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('governorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.governorates')),
            ],
            options={
                'db_table': 'places',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlaceBookings',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('visit_date', models.DateField()),
                ('visit_time', models.TimeField(blank=True, null=True)),
                ('persons_count', models.SmallIntegerField()),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.bookings')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.places')),
            ],
            options={
                'db_table': 'place_bookings',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='hotels',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.places'),
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('description_ar', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('description_en', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('cuisine_type', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=30)),
                ('avg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contact_phone', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('address', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('cover_image', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500, null=True)),
                ('is_active', models.BooleanField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.places')),
            ],
            options={
                'db_table': 'restaurants',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RestaurantBookings',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('visit_date', models.DateField()),
                ('visit_time', models.TimeField()),
                ('persons_count', models.SmallIntegerField()),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.bookings')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.restaurants')),
            ],
            options={
                'db_table': 'restaurant_bookings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RolePermissions',
            fields=[
                ('pk', models.CompositePrimaryKey('role_id', 'permission_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.permissions')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.roles')),
            ],
            options={
                'db_table': 'role_permissions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name_ar', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('name_en', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('description_ar', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('description_en', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_persons', models.SmallIntegerField(blank=True, null=True)),
                ('cover_image', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500, null=True)),
                ('is_active', models.BooleanField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.places')),
            ],
            options={
                'db_table': 'trips',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TripBookings',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('visit_date', models.DateField()),
                ('persons_count', models.SmallIntegerField()),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.bookings')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.trips')),
            ],
            options={
                'db_table': 'trip_bookings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('pk', models.CompositePrimaryKey('user_id', 'role_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField()),
                ('assigned_by', models.CharField(blank=True, max_length=36, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.roles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.users')),
            ],
            options={
                'db_table': 'user_roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TripFavorites',
            fields=[
                ('pk', models.CompositePrimaryKey('user_id', 'trip_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.trips')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.users')),
            ],
            options={
                'db_table': 'trip_favorites',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, unique=True)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True)),
                ('device_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=45)),
                ('user_agent', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.users')),
            ],
            options={
                'db_table': 'sessions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RestaurantFavorites',
            fields=[
                ('pk', models.CompositePrimaryKey('user_id', 'restaurant_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.restaurants')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.users')),
            ],
            options={
                'db_table': 'restaurant_favorites',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('travel_date', models.DateField()),
                ('guests', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.users')),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('avatar_url', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500, null=True)),
                ('country', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_language', models.CharField(default='ar', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('updated_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.users')),
            ],
            options={
                'db_table': 'profiles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlaceFavorites',
            fields=[
                ('pk', models.CompositePrimaryKey('user_id', 'place_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.places')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.users')),
            ],
            options={
                'db_table': 'place_favorites',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HotelFavorites',
            fields=[
                ('pk', models.CompositePrimaryKey('user_id', 'hotel_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.hotels')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.users')),
            ],
            options={
                'db_table': 'hotel_favorites',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='tourism.users'),
        ),
        migrations.CreateModel(
            name='VisitingHours',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('day_of_week', models.SmallIntegerField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('best_season', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20)),
                ('notes_ar', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500, null=True)),
                ('notes_en', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.places')),
            ],
            options={
                'db_table': 'visiting_hours',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TripReviews',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('rating', models.SmallIntegerField()),
                ('comment', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('is_approved', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.trips')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.users')),
            ],
            options={
                'db_table': 'trip_reviews',
                'managed': True,
                'unique_together': {('user', 'trip')},
            },
        ),
        migrations.CreateModel(
            name='RestaurantReviews',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('rating', models.SmallIntegerField()),
                ('comment', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('is_approved', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.restaurants')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.users')),
            ],
            options={
                'db_table': 'restaurant_reviews',
                'managed': True,
                'unique_together': {('user', 'restaurant')},
            },
        ),
        migrations.CreateModel(
            name='PlaceReviews',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('rating', models.SmallIntegerField()),
                ('comment', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('is_approved', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.places')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.users')),
            ],
            options={
                'db_table': 'place_reviews',
                'managed': True,
                'unique_together': {('user', 'place')},
            },
        ),
        migrations.CreateModel(
            name='HotelReviews',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('rating', models.SmallIntegerField()),
                ('comment', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('is_approved', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.hotels')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourism.users')),
            ],
            options={
                'db_table': 'hotel_reviews',
                'managed': True,
                'unique_together': {('user', 'hotel')},
            },
        ),
    ]
