# Generated by Django 6.0.3 on 2026-05-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
