# Generated by Django 6.0.3 on 2026-05-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_profiles_nationality_profiles_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
