# Generated by Django 6.0.3 on 2026-05-16 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0003_profiles_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='avatar',
        ),
    ]
