# Generated by Django 6.0.3 on 2026-05-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0004_remove_profiles_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='profiles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
